from datetime import date

from pydantic import BaseModel, ConfigDict, Field


class TaskCreate(BaseModel):
    """Body for POST /tasks. The id is generated by the service."""

    # Strip spaces so "   " counts as empty and is rejected.
    model_config = ConfigDict(str_strip_whitespace=True)

    title: str = Field(min_length=1)
    city: str = Field(min_length=1)
    due_date: date | None = None
    completed: bool = False


class TaskUpdate(BaseModel):
    """Body for PATCH /tasks/{task_id}. Every field is optional."""

    model_config = ConfigDict(str_strip_whitespace=True)

    title: str | None = Field(default=None, min_length=1)
    city: str | None = Field(default=None, min_length=1)
    due_date: date | None = None
    completed: bool | None = None


class TaskResponse(BaseModel):
    """A task as returned by the API."""

    id: int
    title: str
    city: str
    due_date: date | None = None
    completed: bool = False
